In [126]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

project_folder = os.getcwd()
for dirname, _, filenames in os.walk(os.path.join(project_folder,'kaggle/input')):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/Users/haiho/ShopeeCodeLeague/ShopeeCodeLeague2020/1_ORDER-BRUSHING/kaggle/input/.DS_Store
/Users/haiho/ShopeeCodeLeague/ShopeeCodeLeague2020/1_ORDER-BRUSHING/kaggle/input/order_brush_order.csv


In [128]:
import pandas as pd #imports Python Data Analysis Library

df = pd.read_csv('/Users/haiho/ShopeeCodeLeague/ShopeeCodeLeague2020/1_ORDER-BRUSHING/kaggle/input/order_brush_order.csv')

In [129]:
df.event_time = pd.to_datetime(df.event_time)

# Submission format

In [270]:
# Submission format
import pandas as pd
import numpy as np

submission_shopid = pd.DataFrame(df.shopid.unique())
submission_userid = pd.DataFrame(np.zeros(shape=submission_shopid.shape))
submission = pd.DataFrame(columns = ['shopid', 'userid'])
submission.shopid = df.shopid.unique()
submission.userid = str(0)
submission.to_csv("submission.csv", header=True, index=False)

In [272]:
submission.head()

shopid userid
0    6042309      0
1  104804492      0
2    8715449      0
3  190969466      0
4    2859407      0

# Preprocessing

In [130]:
df = df.sort_values(by=['event_time'])

In [133]:
df['orderdate'] = [d.date() for d in df['event_time']]
df['ordertime'] = [d.time() for d in df['event_time']]
df['orderhour'] = [d.hour for d in df['ordertime']]

In [136]:
df.head()

orderid     shopid     userid          event_time   orderdate  \
150060  31075200506751    6042309   97707522 2019-12-27 00:00:00  2019-12-27   
25985   31075200506752  104804492   97707522 2019-12-27 00:00:00  2019-12-27   
81020   31075200506753    8715449   97707522 2019-12-27 00:00:00  2019-12-27   
146598  31075201870570  190969466  170182475 2019-12-27 00:00:02  2019-12-27   
80355   31075205798264    2859407   12532131 2019-12-27 00:00:05  2019-12-27   

       ordertime  orderhour  
150060  00:00:00          0  
25985   00:00:00          0  
81020   00:00:00          0  
146598  00:00:02          0  
80355   00:00:05          0

In [287]:
a = df.groupby(['orderdate', 'orderhour', 'shopid'])['userid'].value_counts()
suspicious_shops = {}
for index, value in a.iteritems():
    if value > 3:
        suspicious_shopid = index[2]
        suspicious_userid = index[3]
        if suspicious_shopid not in suspicious_shops.keys():
            suspicious_shops[suspicious_shopid]=str(suspicious_userid)
        else:
            suspicious_shops[suspicious_shopid]+="&"+str(suspicious_userid)
print(suspicious_shops)

{147941492: '147478511&163220673&199110270&208806468&58009118&2812894&77645501&78274359&212480041&164098479&50499134&190222721&43652561&4769572&211429582&205951406&213906397&89835507&59282182&189029587&71026438&88732127&86875149&208806468&37434703&50499134&197551102&213526271&52097335&5333888&95619116&7616036&16950820&86051997&213787697&22184&164098479&205583383&86875149&166081737&208806468&52255254&80060796&13487830&205951406&7616036&154598501&52097335&205583383&198218978&3142265&203538523&3142265&9613337&210362283&195350861&2284151&208806468&9613337&3142265&19970394&206794371&88587531&197551102&23857471&52097335&84226482&12282583&58009118&45163392&199110270&190222721&113418397&43652561&3142265&3524519&55372731&1997501&9535411&213162186&203742758&206585991&50499134&101092594&103256866&3142265&48793634&113830512&164098479&205046026&186403294&205435395&107331095&207802408&29815158&104066552&19443866&23961096&52415138&80060796&3766486&208806468&7872248&30279967&55446317&112716544&5225525

In [288]:
for index, value in submission.iterrows():
    if value[0] in suspicious_shops.keys():
        submission.iloc[index,1] = suspicious_shops[value[0]]

In [289]:
submission.head(100)

shopid    userid
0     6042309         0
1   104804492         0
2     8715449   9753706
3   190969466         0
4     2859407         0
..        ...       ...
95   33380999         0
96   68973461         0
97  163522251         0
98   32504026  10221040
99   84711731         0

[100 rows x 2 columns]

In [290]:
submission.to_csv("submission.csv", header=True, index=False)

# draft

In [135]:
df.orderdate.unique()

array([datetime.date(2019, 12, 27), datetime.date(2019, 12, 28),
       datetime.date(2019, 12, 29), datetime.date(2019, 12, 30),
       datetime.date(2019, 12, 31)], dtype=object)

In [191]:
df_groupby_orderhour = df.groupby(['orderdate','orderhour'])
df_groupby_orderhour.size()

orderdate   orderhour
2019-12-27  0            2670
            1            1556
            2             802
            3             543
            4             285
                         ... 
2019-12-31  19           1945
            20           2163
            21           2258
            22           2405
            23           2514
Length: 120, dtype: int64

In [212]:
# df.groupby(['col5','col2']).size().reset_index().groupby('col2')[[0]].max()
df_groupby_orderhour_uniqueuserid = df.groupby(['orderhour','userid'])
df_groupby_orderhour_uniqueuserid.head(20)

orderid     shopid     userid          event_time   orderdate  \
150060  31075200506751    6042309   97707522 2019-12-27 00:00:00  2019-12-27   
25985   31075200506752  104804492   97707522 2019-12-27 00:00:00  2019-12-27   
81020   31075200506753    8715449   97707522 2019-12-27 00:00:00  2019-12-27   
146598  31075201870570  190969466  170182475 2019-12-27 00:00:02  2019-12-27   
80355   31075205798264    2859407   12532131 2019-12-27 00:00:05  2019-12-27   
...                ...        ...        ...                 ...         ...   
114113  31507183252446  149254894  193333760 2019-12-31 23:59:43  2019-12-31   
206585  31507187390691  147941492   40258063 2019-12-31 23:59:47  2019-12-31   
126212  31507191066628  187123853    2338306 2019-12-31 23:59:51  2019-12-31   
160657  31507191066627  154074176    2338306 2019-12-31 23:59:51  2019-12-31   
179881  31507196146800   31844790   95161930 2019-12-31 23:59:56  2019-12-31   

       ordertime  orderhour  
150060  00:00:00          0  
25985   00:00:00          0  
81020   00:00:00          0  
146598  00:00:02          0  
80355   00:00:05          0  
...          ...        ...  
114113  23:59:43         23  
206585  23:59:47         23  
126212  23:59:51         23  
160657  23:59:51         23  
179881  23:59:56         23  

[222599 rows x 7 columns]

In [172]:
a = df.groupby(['shopid', 'orderdate', 'orderhour', 'userid'])

In [174]:
print(type(unique_userid_in_1hour))

<class 'pandas.core.series.Series'>


In [173]:
unique_userid_in_1hour.head()

orderdate   orderhour
2019-12-27  0            [97707522, 170182475, 12532131, 195903090, 128...
            1            [30280485, 11424169, 51981728, 93910369, 69925...
            2            [169046011, 3110472, 212970579, 175336440, 188...
            3            [180160633, 102794063, 159315857, 200116970, 1...
            4            [214236745, 168156000, 70815930, 22800224, 332...
Name: userid, dtype: object

In [177]:
unique_userid_in_1hour.keys()

MultiIndex([('2019-12-27',  0),
            ('2019-12-27',  1),
            ('2019-12-27',  2),
            ('2019-12-27',  3),
            ('2019-12-27',  4),
            ('2019-12-27',  5),
            ('2019-12-27',  6),
            ('2019-12-27',  7),
            ('2019-12-27',  8),
            ('2019-12-27',  9),
            ...
            ('2019-12-31', 14),
            ('2019-12-31', 15),
            ('2019-12-31', 16),
            ('2019-12-31', 17),
            ('2019-12-31', 18),
            ('2019-12-31', 19),
            ('2019-12-31', 20),
            ('2019-12-31', 21),
            ('2019-12-31', 22),
            ('2019-12-31', 23)],
           names=['orderdate', 'orderhour'], length=120)

In [180]:
unique_userid_in_1hour[('2019-12-27',  0)]

array([ 97707522, 170182475,  12532131, ..., 138483848, 132980262,
          923220])

In [187]:
for item in unique_userid_in_1hour[:5].items():
    print(item[0][1])
    print(item[1].shape[0])

0
1511
1
841
2
440
3
306
4
150


In [208]:
def calculate_concentrate_rate(order_per_hour, unique_buyers_per_hour):
    for item in order_per_hour.items():
        print(item)
#         concentrate_rate = order_per_hour[idx]#Number of Orders within 1 hour / Number of Unique Buyers within 1 hour
    return #concentrate_rate

calculate_concentrate_rate(df_groupby_orderhour, unique_userid_in_1hour)

AttributeError: 'DataFrameGroupBy' object has no attribute 'items'

In [222]:
group_shopid = df.groupby(['shopid'])
for name, group in group_shopid:
#     for user in group['userid']:
#         print(user)
    print(group['userid'].unique())

[196962305]
[ 2854032 48600461]
[168750452 194819216 130633421  62464559]
[  4401933  13837190  39828049  73993513  80643747  11753447 102616150
 162847440   8457753  96570515  99322339  81373632  12840239 115025463
  18193868  16021925 143378048  13999404  23352983  77184045  77391117
  90239949    996734  91048722 167932181 180772892  57738503   8838142
 177954889 151362536   6488128 121615825   1668819 151363170 132259411
 115450459  88321715  51586322  93206344 129074211 156270912 184840040
  68444473  33285757  22105044 181195859 136264815  86491592  27099291
 123715078  57956057 185802312  14062776 185601856]
[ 96020473  35220553 185421296  34507155 213907488   8149179  23867438
 136619968 112250289  10251073  12201862 131460045    495431   3827594
  99799957 106672631 191512878  37830887 138613531  27265170 166840413
  40405968 214839304  77424599 188459756   1700969 198765759  34632620
 137587441    546854 211937222  75514903 211192846  30534780  78632237
  89737965  96697084 1

[214781680  73439948  14828488 113115185 214776253]
[ 92192923  35781057 190355845 156702477 182873307  95456536 146709382
  27748642  11089665  37935357   2617982 101859093  93114799  89294190
    237014 183091859  46497903  21064545   1300599  97036577]
[141719243]
[183573973]
[77941861]
[63816183 11227013]
[ 70542895 138672449   1200890]
[112406022  44219114     27567 166027652 164477934  13219935]
[102220519]
[ 16684283 182506959 170960254 195195500]
[1273324]
[166137465  51332368  70617193]
[ 26254595 172676734]
[93242459]
[173285129    722632 121827333  76077674  76905043  46875705  10180682
  59115300 173197838  22390899  14576313    435308    610746]
[174170506   2059680]
[192395202]
[64018158]
[68938790 81815056]
[201940287 122151921]
[85866111]
[ 42990566 148392553  33750191  84152525]
[192897141]
[ 50800332 135140451  45930554 196183912  93448133 117006581  66898976
 100290135]
[121403248 142911136 209446109 214200060    490173 113958390 113379329
  59259911 176288758 160339

[186722585]
[184939397 163012690    182670  43012102 170850040 211151870  41132921
 102815472  15565051  18164816  66414833  63910003  71160670  74768187
  97403498 132324178 188215352 174207123  28080619 117677038]
[ 78274967  15428446  59686251   8521967 110638184 123497176   7437282
 111731490  95459468  34422422  11529818  81570759  31749415 101114993
 103580074  19986150 136701204   4194106 145355094 173944548 101161065
  92622776  65845991  15141807  20679063  43779623  36938131  23804697]
[167194009]
[2010733]
[176058612]
[98859620]
[207129074 144403143 180188116   9544957   5272171 132113554 152397749]
[155695715]
[70027944 69717958]
[118795475]
[244650]
[22219853]
[ 15396976  76247663  45836026  42792500  84950465  77912425  39802423
  22658728 107879819    677460 104876057  63924896 130795878 140014012
 197273179]
[ 31715411 105955664]
[ 11599968 166269321 208803326  85800661  60965521  66208846  43180886
  12088405 187075741 201594388 214927983  89307999 143768996 135724242


[ 71009029 185532707  72437498  85337925]
[112305334 133674101]
[132598104]
[12866739 80060998 21380471 58955788 19516539 43942200 23496239  1144746]
[ 53993995 133340279  23448727 213048065  83741693  10539858  62754982
  97900331  30109796 180498907 212641258 194690509 212742436 144928412
  31999708    214366  56493035 115255412 183379674 158475842   1122922
 101183150  21103345  44474002]
[214923033]
[168164885]
[124108460]
[ 72266748 136705021  15904547  11567869  33656824  42195173 204247258
  44820913 117421403  55737673  25927513 114988180  43921904  23804697
  50349485 126924077 187013024 187099276  26038152  71785794   1235249
   2101151  70412434 212495632 123492745 213682532  89576506   6632407
   6066181   2192844  81523593  39301585 123861555  99517519 127753883
  37417443   7006388  38432790  98568539 100689375  46871437 158139010
  71220574    309740 170993237   6662062  54471326 105304717  88361007
  33046849  65622949 158344631  78017109   5769280  56491210  42314861
 

  99348671 126471299  10161722]
[214350413 181067770]
[122592927 101183150]
[165333438 166280148 182358189]
[50514762]
[ 5314183 36443417]
[214642600]
[196423842  67596533]
[174534559]
[ 14621369 107268684   2106249 183437305 200455021 213071530 190090427
  61848586  46613676 107573520 171615636  88821168  43519195 110949249
 111321297  18432035]
[140098506]
[33153246]
[116592594  60560447  57721431]
[97204721]
[2199472]
[17918810]
[204742097]
[84757376]
[10925237]
[197922012]
[   726256 211355834 200912751 104069750 105218810 114400021]
[69213705]
[ 26805848  75877330 141014481 125404437  15130233   4915215  87613545
 135312802  38796709 116594015  88800227  29081401    740844 167406429
  92347511 122523434 178427449   2029696 214209607 108003911 195803320
 214628766 214692437   4770406 202532877  13292459  43936173  73883476
 214735943 128199958 174467130 100534957 168891049  80826877  97064487
 113110673  90335767  12524982 188572305 215309507  54228148  78280359
  51818858  6707004

[204586595 142775986  60684651 156962937   9656278  17448329  32005804]
[127176817]
[109728336  40159288  51391898]
[172865262 185235996   6704744  47704022  68946981   8726437 101584922
 168155615 195329940 179722982  69754669  50556388   8871697 122837233
  29380334  29442395  27199784 210540309  68618438  48900449  90889581
  59239186 206584001 180848064  42002275  38078021  83035105 112610916
  75607295 121187200 112603379    170551     21525  83720164 150478657
   1070990   1292823  64682619  26980861]
[168984733 154179113  53365955 172865572  90889581 130441105    764315
  17448329  10118849  48504223   2105572  12318172]
[ 59546896 173338072   1918921  17977462 214311504 103967156 107127066
 108339278 103529651 181202364 138209106  14415705 115261202 196722937
  95735457  90736879 214306122  97953877 180387542 194262074 101432350
  56672510 118906845  27635950  49296656 192799358 108041539 103691836
  98016311 191702519  15888547  46357959  99876495  58319869  72039278
 21037407

  41604254 198887753 159755802]
[10326845]
[ 28312307 145102766  75212709   4782343   2551120 215129757 103047288]
[121656748   5136567  41372621  56973920 101997618  34739175 107566690
  90458804  92831953  34348477  47417926 170173485 204178102  65639764
  32112164   4934602  66617822 117255418   1143700  12282593  46370992
 213614217 102713435 153613127  15815803 104129922 215263810  32451953]
[ 32529470 115034845]
[105952460]
[182752690]
[  3170827   6748232 179366272  15203860 147460737 171459446 188537965
 213975472  79289610 117152470   4631317   7395927  29925306   5542974
 100878053  49137504 170783770]
[  1945111    221730  62499188  53347079 135420532  36244711 215281326
 142700932]
[120092302 190531639  92227825  71534182  27194972  63373167  93415440
  92322343  21862886 127461186  15690999  26473076  40976274]
[101776721 193129853  62985692]
[ 95094950 190818427  23863565 118802226   3875669   4626431 213772858
  92244293  85191676 103644382  80978920 148411729 177477300 

[141972876 214687981 112180175 174716180 116417136]
[212097412]
[186428829 183466137]
[165784857 120053677  82272155  12296463 183026664  84224957 118879352
  97071213]
[ 95443085  71693630  75569807  51192470 206022856 138849825   7930476
 153388359 188763823   1912207  18076096 113013938  22326038  65750534
 214634087   8795936 119696007  26096762  38523898   1237927  42052683
 109521796    502793 103583708  56180917 112214113    794856 194481468
   3987196  39998731 167948424  93965916  82665078   1351298    651737
 177952947 110016388 168975009  32597100  53674145 129992846 183491528
 183096528]
[ 4785488 61508079]
[  4280176 181630787 214151245    679696  47718902   5374050  51061788
 173932983  82146004]
[5887726]
[76156593]
[ 81960857 144762755]
[66110980]
[ 87541933  56223217 199979908 171785236  20419573 179294862  31759746
 111141292  28555258]
[206555945 207087344  25243111 211691194 156112501    887230 140954159
  43487667 181689946   4814784 210493659 205939457 135858050 1

[ 33524113  84997290  38787193  89710016 149265027  17102310 104117651
 153541668 213615246 114428089  15361940 184981405  41078324  55269205
 153349978  45284770 201998192  28618644   1636270 124425796   8128647
  12947483  18338916  14151119 116470071  15529725   2450336  13052442
 189898906  36920864 112739402  79432575   2973390 132195640  10147542
 144777942  15199961  99663949 189013307 126234433  22455807 192075477
  43497498 170803493   7089204 214223704 177261518 165279507 107655629
  99755241 113015260  22076561 161310551 212144171  40302701 214448024
 203067253 183241682   4475857 142875917  12866739    619155  10748452
 129788917 186965669  82928772   9941139  94769462 105870710  15988501
 212768587  91279485  47493349  76602044 141044221 174478488  11248244
 173686476  91026847  47460166 193979607 208214778  46431578  76678781
  26453072 214604127   2908972 189744394 164622131  95497850   2303932
 127668008 112253001  55748363  51190088 120812603  58147967 142848435
 20586

[128755891  18418771  52783964 107820830  63419868  13112406 160024500
 196736751 197823733 141242046  80899963   1022069  34458155  20678256
  19599140 185957683 190834725 193009680   8480249  12899324 211519189
 132068305   1879136 181565644 147806936 176211440 107197455  11177230
  82011078  83907958  75731545 186737173  17348624 212722008  42762508
 196769173 103459613  89041182  75552654 154758587 151703742  29282265
  88724643 156286801 208775652 114020937 160658870 206674608   5821666
    505650   4366074 157542883]
[110591289  59297643  71841763  98339848     92968  15495758 200207546
 214906763 194793766  75069816  15410652  97304245  96489976     23251
  23847026 147551257 125358460 155349621  90639894  59920840 163523567
  61235299]
[153541865 214933533 213125124]
[ 81410812  99480021  18103880 204658029   4378872  80702620  31508621
    228012 114287609]
[  4932346 105114139 173072028 138647244 174347313  15575023   4247606
  15022032 181171693 206591517 118142395  15479494

[ 82731106     28068 141390628 180945094]
[92810486]
[174645040 168322036  33995610 195107802 204054693  19023566  27496253
  75673363  36634493  31633868  40556647  94520594 214973258  88388074
 185362812 107550277   4096507  79416859]
[  6852208  39787208  37464802  15251153  19806099  15614077 173543160
 148803017  39398326 182985722 189522371 215022289   3297514  23422389
  36734666  22363717  83342444 204590703 165656164]
[33218916]
[202272968  65253851]
[2044578]
[25898625]
[ 48452741 153288437  64945531  64373922 163663511]
[ 12088426  95997153 108089017 211166728  13461098 156667573  33466921
  41550256  60017456  37559136   4796635  96240982  43071146 161079570
  69101749  44887741  69474248 196214324]
[79124751]
[ 99566114 121897961 130482833]
[172709741 192122449   1994400 182873307 118188490  51384686 135532264
 210595201 130304968  93757540  21767927 142016060 155795058    396861
  42411714  96638385  19251904   5129690]
[146756847  26235600 136602754 158274308 154369164 1

[132294130   5943416  90237998 122674268 186737287 117837543    402916
  42685844 144534291  90420761  44531773 168588404 215292764]
[ 36574537 214980047  34899989]
[214327596   5883240  43017987 205785539 158334366  12232876   8882288
 102982325]
[ 60904311 203239709  11531953 167080106]
[ 91524204 201303388  50262386  14849174 173932983  69977634]
[ 18101954   3221569 120334021 192832162 186291731 142902138 198385913
 128705463]
[150078988 153868837   3806446  27157989 142841955 158956304   7070236
   1939777 132358404   6764413  97715158]
[146272252 130171765  63080702  52351108  61289402 195089151 127757551
 183337635 200427289  47651912 108108101    281139  95497850 102221548
    955094  42865451  95703687   1315210  98309169 214359681  95702362
 130100964 156482481 152177127  47484137 133013703 156098495  20247133
 120054085 175104503  42979212  39874606   1308280 212617959  68454338
  83181998  38659228 197546698 192868950 197488881  99107113  96950700
  23027288  69064573 11871

  42073208  27862704 210911406]
[ 16851522 213602269 133703895 212991838 185372793  84273084  16081367
 120840089  49133456 113283867 214599689 122490359 107789847 215245058
 182652124]
[ 12873160 210886665]
[184666340  53129368 180197895 100029511  14558982  36369732  12180876
 196717727 154998636 178091782 215288319 215459882  94554596]
[  2303012  70986759 168796759 118061957  80899963 195124455  52817486
  25664537 165923886 154423335 152464092 208866850  67508754 196957522
  98735027  91736753  59123293 201945653 198207037 103475228 117751318
  53240220   3961470 212430313  53393534 105030690  93637207   1918921
  88955513 195416579  58348630  92423762 102281173  50256343 120912170
 102656257  12320039  33185349 118950813 114085386  82440555  95703687
  72544435  79381031  96638385 116978926]
[195882549 118885127  15338615 202699759 143639611  94380353  82090102
 183955748 215304041 162929464]
[176934841]
[73729309 11735910]
[ 11792419 118781591    330690 101444198  86084750 10365

  41834711   4809959    608642  47154104  93290990  68090345 113335477]
[  7310165  51725126  34212330 167927964   2755366  45471450 147578845
 153081043 154044472  30691057  93783535  27664043  26797589 183980174]
[ 33391437 201883904 129586016 101868912   9681660   5551292  18642757
   4416026  17971780 100271197  74412767    910702  47697776  98209232
   1274613 168930207  12562225  76493311 193690068   2816527 184188882
  11729378  87123033  57348111]
[ 99913840 118312555  53981024 182250456  37590028  69817933 120484647
 157752890 137196353    147487  16529133  46694777 135193487  41378336
  65808964   3290616]
[ 71981700 105720226 173121770    199691  64547943  79239008   5810442
 170081817 211762035 196794916 102663684 185361512 183458808 141609377
  78834157 165862751  13854809 182154231 195463301  43083569]
[ 69639059 146326099 207398468 172357969   7657709   7056642  60739767
 112096858]
[173367242  71261655  50547436  46486437 100547920  77447798 116486940
 152827647   52180

[140260305]
[528022]
[3675748]
[5790619]
[ 89203576 107814303 177639224  41755160    186540  11206250    103120
  89173990  95232551  54710487 195123368    495270  32742511   9777890
 168345929 102776138  56219136  20289983     68925     75901  10262997
 183513069  27850225 164532800  33476007  11045993  43462616   1546983
  59697462  47165271  62774905  94426978    242027  39156445  31648942
  33121342  90645805  31330109  82595713  36677608  96000734 123138795
 189353258 136489083 196186394  19449673  51881272 144115333 186143147
  90807673 150500084 135948703   9012491   4463442 109799260  65055567
  29119948  27139496]
[15702890]
[8869743]
[211166728  66251378 127561102 117363831 116777412 181814785 114487894
  66691604  42388238  86420236 129233535]
[184912032     10324 211976125  24452293  92219572 197239134  77478825
 153187732  95565389   3478642   2981666 208655147 189123279  48774225
  40243797 100296354  46694777  86403659  95736512 215138922  65568672
  99030602 175320894  

[203617000  29619383 103522966  35016214  92202445  59543454     79013
   4132082  16550529  14710237   4801754   2033667  63652552 182383682
  28310222   3537125   1422837  41355789  85909729  16684283  11053397
 119618046  14728872  26177779  29600692  66670689     10359  49220493
 104097606  45891208 101242731 214622910 110330558 191817822  30775333
  89028324 100689375 159545589 210710284  71534182   9331833 104853151
 191876968 136701204  13923684 106644578 170937149  40705667  35032606
  57755699 171158121 154573191   1833034 202133818  68539785 159241122
   9565978  40175281   7407713 180102231 132922484]
[156355513    869084 167399877 117366901  37058976  26479015  42672387
  16367704    908985 207385828 123677259 116802187  75920855 211247064
  33022997  33363482  26181828  32328954  29408000  57496952 214617593
 214615657  21037542 152742801  57908179  12162745  31537211  58659577
 196757019  79702598   3201499 183151713 188188615  42770147  49067072
  74823356 122113630  603

[169463927 107566824  49749673 119264070  79399214  11567869 148724269
  11753447 205815748  88881456  29891724  65190907 125514394 182506959
  68159997  33285757 201907247  99288957 155539632 214501900  18399913
  46812333  54395193  74921110 143888220 144580465    330348 147939302
   2211137 112184334 177105432  35619220 110703586 120413668  88301204
 171311505   1272105   7648563 173580330 143861856 158688578  93503912
 123040764 214776682 169197512 109729409  62929511  44631466 189107831
 152164374  36072887 124132626  75213205  38372041  52121262  33331805
  26634765 207140862   5814938  97897019  89275690 139638525  31188462
  94638182 133727752  86921988  89288861  43788367 214290363 114558017
 208091818  45341116   5607816 197531955    936018 161858752 157137651
 194895618  13578131    301452 177673524  12236281  57755699  23866564
 175718720  60695997 163922234  37144123  83314670    337615 114217636
  88855363 174477523  42930445  64324237  27877969  56061153 181017924
 19594

[213587321  18491853 207310288 172997365 138855897 194201709  86321897
  19349638 146353732 152451791 197820751  88648111]
[ 78865449 132158275  72230043 135549661  57437733 214581417 114593306
 184840040 204025592  62558049  58226205]
[ 25661937 205192160 211181534    229829 183241682    667208 141669478
 214565727 151742558 211262942  88788660   6274969 151057012  87347760
  10714834 172593197  48024705  10234248  39200590 186205889 104504926
  81799048  33009358]
[129962385  58482987 194398273 214629981  94553351 125711239 120488507
  87567843  82075657 202774392  23886800  18262767 212676037 139398997
 104446134 110933890 212312729    820471  11893694]
[ 46408526 145398899]
[103570018  95410962 165332569 122801106 191433486  73929335 169393818
 104437408  10622015 147313315  79950258 204705889    629760  77477891
   7989445 206248169  17778090 158851182  42233670  19916061 165646694
 215158231  56267106 167840528 183587927 187786508  25509394  52541274
  41585262 179279978  5391962

[206385864   4600853  89589935  26752621  27241023]
[ 82384645     66285 185683308  16848403 125495945]
[  8368091  26680849 100271197  80009146 140193724]
[33244778 64160014]
[ 34367112  26824926   8070323 170502711 154941815 104114506 156449687
  45930554  90062828 142224898 161775085 177128846 179722982  53597253
    187265 109548532  68529930   6528393 102050877  89331421 167668189
 108101291 133170752 120689302 154164018 213969160 161081080 121575524
  72456985  99986350 191078647 160935202  81794558 121485417  37977691
 124878485  92310100   5332147 167121504   1123964  75514903 187240020
  14563744 206807200 144263790  25186995   8034686  47784822   2741336
    245487 200972931  22671133  13219935 122878851    122949]
[214549449 139830255]
[1843572]
[182260748 116052791  34034010 189668978 126479284   6854891  97341594
  35746787 178722414  48977090  40654577  49295128  69173854 112111391
  84270446 183959532  57720287 204717343  93849818 170655354 100294175
  26000970   7904131

[122479305 122974552  39814913  98978204 175250406  84897590  89016705
 171276556  75621637   1748238 207382093 214343777 144367835 174739594
  33303585  38772235 111970984 214527721 211852511 214548164 103531306
  75707142 213747171   9790441 126410843 163397554 183468867 181261667
 214811376 214851757 105541087 214870568  89031372 214409756  87552092
  51314788    712374  17642950 214951957 129035033 163648125  89041210
  33612719 203983906 171836575  45970098 198639234    319714  59340402
 138913762 111396280 215103525 215107013  26985207  94914273 123622161
 214773669 174130737  29118578   5156569 185413067 151863583  89029913
  87697215   2235758 163884080   1031963  44276682  79056640  94225057
  93797860  15527803]
[ 91112850  65427223   6475737 140544956    606474  52626352 101489720
   5519982 154419952  16165829 165955128  65174717 153808484  12768809
  50349485 128480380 120008110   1539896  48224261 182957785   7828552
 105026531 208243312   8191814 195123056   1418195  343

[5575322]
[23516353]
[53059982 94957287]
[196547592 129296854]
[213890939 110866874    242979   4498261   9348470  54327507 142962103]
[ 50502962 184597240 124394053  95497850]
[125923543  47162603  77577924 103323244 214579476 174941446 165679972
 122611588]
[ 18149508  63579780 111302775  43494116]
[ 79632357 207877850  66308280 169472345 179702288   4280854 109782579
    226389]
[ 33524113  38787193    313630  12276392  41355789 157022620  30985838
 113647157  58855210  86606816 115642559   7775458 129586016  11392536
 192793527 133777600  32007753  75776032  28618644 107331095   7765930
   7228943    227995 106522149  17082627 144590319  75677053   7839413
   5223632  39657599  35010324  53415124  17006432  78740283    250016
 170150287 101850859 101124243  95897511  61084860  58504576     45748
   6208440  18520022   8898605  66297149  33379529   4192623  17323362
  47589342  33922830   1000390  57237408 155425799  19072201 212934132
 144967521 207257335    594519 116468388  44312

[ 10462121 214917940]
[ 19235891 124510069  97497583    919915  54719569 130297421  74962396
  79031524 117511293 159207989 127076548 206970875 153535660  57056368
  34899989 130270748  58160112 153838910]
[ 17861947 159101398 127668008 156226600  34939373  57628463   2256507]
[   711654 110712701  37459528   6268746 202364847 134697722  10409290
 170150287   1405239  92011463 173211987  66562588  14717002  42896198
  83395832 202385134 102710762  51197737  77251941  11154038     98177
 128645401    487812 157306216   4096507  98989791 120619092]
[ 35365832  97927016 186372710  12440730   9987867  87703329 125683576
 102549652   1577825  84913503 114568045 151267240 214500969  12772437
  60370723 199891702 141186268  19470262    290598 120660475 192823160
  72485287 193770262 190117542  51063049 213630903 115205673  18840123
 129696826 204746592  87819023  13590085 162862533  55375223  56938296
  75786255 100522994 171210198  62618890   8882288  91377057 148164793
  25950797 162150114 

[ 66253796  62003344 193520748  91243255]
[ 72629595 149631146 201883904  99477692  50673457 161988020 103764430
 143470549 190723823  41755160 211684260  14996822 207396492 112325125
  97380109  11807266 187692249 160371503 104655022 190924331 202023655
  51420920 134291397 140289042 165792813 100175689 202063714 183601002
 170732116 134480872  36964052 214590255 150442321 210536432 207205154
 175036868    804812 129451137 129980733 187353799 194695491 162478624
 100712687  37589864  73349465 127193177 175946221  64232218 148729075
  95873940 196700358 212777623  73692660  57893495 115256507 168250545
  17001396    228116  59268934 209234522 184686059 214916116 209512608
  28835258 202275043 111037516 197941905 175764919 182566015  44880599
 212755212 190309868 169947930  16869864  44942437  67632376 119918700
  12088426 154985478  29498581   1229725 178342088 190656013 117228811
 166289110 215001311 160757564 175781930 147934057  69424359  13553403
 138203696   9751495  76356937  885

 122676182 169207878  12939075 202820734 128162220  69808959]
[95985420]
[ 46360514 175354010]
[55828609   680038]
[183184152 100445423  31044985  21123954 160769071    933766  50732500
  94740983 197088533 194473424 107575113  87291506 103320676 209743740
 195486094 215403539]
[130470760  90089735 126795400 168223685  31124016   2862244 172952277
  44951566 208345805  62919711 149610926]
[  9059549  93369430 214451166  97766797 160971621 135289652  57577445
  53989443  64067459  55601578 202807746 129645069 215150772 207305529
  42767696 159061294  76711867 103287780]
[   450199  24783861 193974358 110618291   4070727  30442127  72847196
 109884077 170211872 205354541  64470487 136602754  53328034  28948180
  77412755  34718157 117389549   1167691  13160330 172766973  84125419
  95679660 212046473  73267445  39196739   7804135 189715104 101579301
 120672285 209321977   3461940  98411104 181556170 193009680  45038058
 152446053 213777008  67554410 155647625 139968925  46031108  3965759

[202690719  53141257  79593708  63123401   3263901  53646629 187641401
 188337058 210978360  49696139 199401338  99440238  76892736 190139176
 200638755 186606647 170998921   4012323    781461 184914593   3008641
  67206885  92535372  60441028  45314477  96046105 106963524  88974878]
[177864152  50792934  38666018 138372839  55818045  64098889  19023566]
[172793051 110720993 144791189 153387675 178923370 122450492]
[195439932  72964427 143087248 194244146]
[153868837 101328454 186548362   3519881 179158703  29353137]
[ 92200187 168078140 197299445 193936802]
[179077871 132425026 189875765 102978451  76290513 209974465]
[181033491  95577071  67508754   1373193 134318054 167347392]
[ 17203270 194689826 205171602 111285231  93118703 179252575]
[  9841837  16704994 157794812]
[ 91416788  86500764 144651035 135074470 178500475]
[ 81495241 188987647 201627780  43935491]
[ 76412902  45281247 177328811 199937257]
[185516240  72795955  50847163]
[ 47716446 160382478  26214674]
[ 29501110 214161

[178676280]
[64146458 13742705  4040527 22589419 88477564]
[189090862 214923033  10102337 179005389 107190758  99531405]
[157916011]
[ 85169220 150078988 213849905  66299858  14034814 203469225  42514255
 160621424  46557588   1424055 159692407    486392 214219266 119447508
  91175097  89274747  26789065  80899963 141019365 101865275  28917145
 101180677  77730076 146612625  43068423  63493712 186941682 177434209
 112452545 146897414 166912663 158363964  49575928 117154431 196759853
 197872587 103621622  74412767 207584366 164080651 111302775 159977397
  69512790 103042865    592243    562339 186147599    213280 129242023
   7961172    799236 121230433 164147627   1627568  86203069  86827085
    300461  26796837]
[106916516 141613568  56156876 134227883]
[152919516 144780413]
[171926422 159899936]
[  1817633 143265517]
[  2680779 193132977  23911508 131600513  60352193 171148926 206148402
 181899400 198785679  44149242  90789966 112489336  49451907 192485468
 189960520 184535087  20268

[97735455]
[206679603  69526547]
[985306]
[213584004]
[146648773]
[159463418 107573520]
[62093464]
[   598098  81009215   3538304 194910716  27901686 173437517  35687009
   7163614 211336186  46756635 140748603 137558231 175697831 157176051
  94301451 136079603 151436299   8638713 173608957  93290620   9948399
 164982710 212172440 117345351  78342222    839022 204217787 165862802
  14160704 183811411 102971939   1561773  29119948 167699111  71562280
 197349247 174130737  64354521 204125541  78613503  13492431  83620942
 103050396 111599441  87447312 174197738  10394571 105086545 195105977
 124554536  42005925 187225100  15978178 190485508 147129961 137918368
  85064717 110570398 163786642   8301268 139845980  67053040    213436
  56312463  45148515  20875352 195875206  53203830  50902365  51442744
  12954546]
[ 90239250 165202723  48916921 177058895 214522763  16365612 212456364
 154689269 107634088 104768484  80953476  54024379 171833814  51457695
 214682296 129083479 172291881 185715

 181385415 111919541 152179125 170783770   1840238  56164468]
[ 52975661  12779390 107567306  36399903]
[204898261  19364825  91361155 207073462 208123545 165220235   7610605
 174418977 186050973  78918895  19952484  15865730  40935803]
[166727279  95497850]
[211110611 105521506  62651025 131864256 103021144 179014477 146897414]
[ 95703687 214833746  12380307]
[  5530537  95390161 121272301  81145619 144856440]
[  5884766   2307831 135202646]
[197856743 168900761 214361790 200312917 189090543 147628646    348846
  73756435  29190864   5623675 189978730 197899762 133527849 103721551
 180812814 181076191  70027490  77812151 120841361 121100636  57122238]
[ 98960849   9837180 128554149 113447891 127398759 103644382  89011065
 183354778 210974650]
[ 80379884  87071532   9384152    645644  37740006 214599985  88348964
 140401094 170722720 214671371 104980488   3155878  96676624   7408649
  85597008 103890087  35239739  70889397   4183607 189587697  89161415
  46236926 119719360 215129398  7

[ 80022509   4035608  28858329 174542882 204004832  56290308  14977046
 152732705 174649805 175295652   6605234  96556880 157651038  91355031
  39838790  56236714]
[86365261 48016427 51257034]
[ 40615251  34502302    337377   4192220 197584965  80687990  94425990
 178127589  32315109  58305973 160403313  17173901 161047829 192891699
  16535750  94523191]
[ 57655947 204106030 117542226 143725841  95497850]
[214326533  78291048 121729330  43783740 211907148  20164175  91023591
  80375906]
[173634081 127279390  60324918 155536956  85405673 114338392 197616130
   2104188 164163813  90588251 182244671   6370147 205785539  66889129
  13923194 115650462  19023566  69493363 169579115 212799981 214899890
  37690155 121634128 105697251  63592562 178185493 214743098  30516434
   6324349 169102242   3769843 136834141 105549258 127126031 100420864
  68304622 121780936  74510092 190408627  54255168]
[194677654  41286642 191503435 142293292 188560637 107685660]
[6481089]
[   817280  40859096 19560942

  73689728   4979889  36750049  76493311 206926824  43749188    494644]
[160611062  67341739 111273180 185072771  14034814  29769754  54550072
 108013873  20248746 156537239  68680945  19621335 184890204 193674884
   1953668  11799638    539978 126966473   7416995  20370468  10976071]
[  8815560 208880577 214249296  37227086]
[215339727]
[36888507]
[ 35781057 182525910 208696933]
[159208307]
[156198334  27653318]
[158376984 154727063]
[195124455]
[187207868  29199374  44473968 120237868    141438 185579048  67276286
  79127624 168197506 215440744]
[ 98115542   5259861 153541705  83240660 206612827 160761168  37920091
 173745768 116960757 199342204  16684283  87173336  85454840  29019477
  56646614 169273953 162784558 212237389 105960344 181478615 120484647
 134776979    399981 141509926  42922274 130451459 126673595  87377269
  79981817  58556196  74187906  27241023  44038368   2219753 122975576
   1000390  66775379  49171998 125910942   1180448 104647381 146495950
   1009986  81638009

[ 67785564 146597366  39642786  99224465 173386347  95500119 186221011
 211353655]
[ 66971922 163961989  81007923  94005455 118513254]
[ 22408025  86374003 137746233 149691938  55502220]
[134768499  39501561 181420528 108469803  60888216 103731414  19590624
 131289063  12339610 171121857 192666517  98699996  26000970 178633962
  42700374 176690067 175769229 174932371  14426372  12443891  15694589
 201812481 103345740 142549919  96090370 195620462 136650015  70540468
 130550982 131332294 141384807  17044755  46321223  51418976  31229372
  64811660  65811673]
[149773145 157836204  84770994 187249519 158851182 146861700 110119426
   1327524 179499370  14985195 117846068 190997025  62730442 195374763
 114887807  62855088 110859991  88839712  24158280  35594072 199300463]
[147222990]
[177522240  99174939  88423556  88615321]
[147456796  67185516 100224660]
[136465606  84490651  77822964]
[ 94580408  28979079 102432743  35220553 161192523 144097665 103815141
  81205318 214619361   7791783 21

[  1918921 153225952  36053066 133006545  83683866  69145871  53644865
 173890946   2290950  73602759 168531437  43198336  77469154 198025843
  10305023   1651572 146997400 106479654  30690363 203254894  48741346
 154994380  62205407   9585434 194088882  14512626     69478 136834141
 182193465  69191562 112814445  61437929  73302471 138975557  24096641
 103869959  55153514 120754456 163730013 130388528 165786344  72169524
  49085799  14940714  85597008 132519927 150930953 191041932 153541668
  95425827 198954492 171653839 213164645  95299384  13727299  44398593
 211548745 167094034 202913480 152350539   5074266 124411671 208306749
  61484630 120704604 139661901  64106900 192226918  98248450  18348981
    802231  28256090  14900470  75497666  27405629  94780070 102911602
 105620386  14562798 128408321  85259988]
[163109213 110973620]
[ 97707522  17778090 178312107  44945690]
[187029539 210863479  93242459 210446206  45638117  77378802     52635
   2816527]
[204321778  49150259]
[2070215

[ 41220248 179077871 202206176  11062779  45393579 131868382  22532045
    942952  14993405  62495033  28991337  29177639  53626372 162494222
  26871786  13929816 117109154 183243169 139034663 170936417  31795400
 201940287  54939316  35908528  76905043  56253454  66200072  48376027
 147434915 136257732  64560738 129803860  47153693  18257403  14767903
 175829142 200008582 140679121 106971721 115581143  88103014 200957409
 157690517  55443428 171477179   5435107 181385415  77978351   6282555
 109994846  27662499 106560139  14691988 190728548  23804697   2108522]
[165936731]
[305182]
[198490128 194580251  30627825 194014348  38634748  87550098  35054282
 193166009 158064057]
[153974957 104583836  13112406 140849956 100555714 198024744  99341072
    414600 214255025  45013816 141433822  90102761  69163549  16130155
  39398326   7002306 178182287 156270912 153538082  34280998 192417131
 100344378]
[ 15866121  75920855  33272869 214747020 119651315]
[95729950]
[208722377  81639233]
[ 19686

[153969146  39893987 214289448 102957273  75816609 130040888  85021385
  58585091 151581657 153541705 201248862  38912849   1625192]
[ 82718026 129044685   3539707 104035987  77377491  91393229  89023743
 180999530 187949845   1657423 119304087  96238497  97526902  16072796
 167773530  46116534 214710869 177456769 134719128  97813411  75624779
  14732076  86488862  61686160 182361080 165448160  65843405 190714428
 126322884  61029608  15418071 106742649 139702353  15819405 116236169
  15702890 165174368 213536598  96276032 174493871  86491592   9517159
  40850362  90992483  70294833 104814026  33209545  68375355  14637850]
[ 70128867  49671849 137187065  18491853  14005378 104826707  10907359
  40615251 123595810 142710562   1969991  92424346  19481356]
[122900829  99400474 169041393 209940101 173508931 195586816  88947651
 211601101 125711239 174688549  69600678  39592911 124755431 201877955
  76914083  15935874 208904558  55674443 124917704  64495742 203262157
 132954090  45312748  6

[140959692 214289448  73267989 214402513  56288280 182948158  18466442
 199246873 101300214  52237433  32219241 164153239   3495625  13812011
  10937463 113996623   8170753 171674574  12204819 180326706    588007
 172551609 215321020 185387042  16636723   3679069]
[129586016  47028057 142235344  15130233 151215576  72078936  81943174
  96551500 104170255  27310880 206937071  96095018  19720391 124531729
  82145283 175355414  45177275 127749924 173595240 135134030 197614052]
[214092878  89020820    296629 103540096  30043164 122893563  61001335
 141382978 182191648 175765995  99405717 155162601 164529570  51209276
 182819295  12597591 145578359 133261175  11170845  44072568]
[44759672]
[154526237 214087262  34925222 131755250  28482250 164723652 210853305
  64350865  95606907 140074272 150681065  18101356 158833283  41587548
 163384280  65738835  78004131  20484605 208249363  35596082    513940
 180764784 125613108 116117314 118872455  44417531  49085693 201262595
  80337490  28482762 1

[153541705 137202987  29287519 101892127  58987755  34628464 154179237
  50490044]
[ 32275608  31225403  49363179  85128406 111659010]
[ 98791039 117104131 197007992 109971879 168521301  86679446]
[121626503]
[  5350578 214490025 213816906 116615053 121516580 215419932  97555021]
[  1022069 160276734]
[123874803 172326485 111512375  63833267  97927016  88682025 205680949
 132200605 153189200  41961190 111307066 207877803    134229  77210938
  16869864 208255258  15735296   7838158  69383304   1910459 181416232
  71061719 167718371  17449395  27018097 194827767 121198502   9266748
 198168095 111778675    929767  51946417  65114191  92047297 208873341
  89070782  32055108  30139471  87840975  45421468    261510  34632620
  15956408  20126471  17186575  91377057 200558754 201318624 122879659
 164532800 107682955 179905368 186148741  55006399 136663290 178146663
 112677101  20230706]
[141095343  66188644 137613607  19458717  28218625 141493124 179332914
 173745768 188922603  22486196 12958

[  9682543 168048638  94405382]
[ 37589285 111244895 173481896]
[172343429 107719562 117161399  97644424  49698737 168697503 140304538
    205713  87907704 205040214  46395503  33902752]
[140417542   3655530 194293350 115178383 156361417 141673039 213043555
  57820756 141613568 104464076   1939777 215011854  18089854 115223607
 178826961  46955598 169971927    439508]
[ 11739811 207456571  52227853 199703906 129645069 187122089 214408479
 169699556 132626833 211166728 151966399  87086658 101084939 214526830
 214520178 146173580  22984984 184847258 127378396   5280720   2135298
 126874967 148740580    627173 214899604  62717174 141433822  78019637
 135970492 115820550 210956254 170659054  93481054 215176180 119332138
 125815482  28494655  82346926 152824876  57132874  45184075  35252243
  78890294  92355518    228590 104341283]
[205884585 191092115 186526553 122408047 120574447  61422383 165557747
 153541920  30462251  98163488     89350 133809802   1022069  74603478
  74601746 20623527

[3299466]
[169963480]
[ 17441320 214103167 127340795   4101189  49399118 106847495 118614751
  17238208 166389925  30261338   4865050]
[87932947]
[176955327   6792909]
[  5790866 134248587  17448329  47983219]
[199903628 208681428]
[153541920]
[  3316918 139896010]
[ 28093001 167501424]
[ 44474002 174550580  51503985 124447140  95500119   2175640]
[137476239 192881363 197741314]
[ 65648632  82808988  36391185  73432879  19384904 183727168   3594049
  68303946 187615957  30969890   9785706 213767611 101242731]
[146126513  91868771  82644165 151258925 154232889 151358131  33678948
 199112301  32873854   1125309  76266392    967357  89614767 214011536
 200071681 189013307  83105612 135721660 160670408 136029769 172244332
   4859929  22758059  62911642  58428306  46388757 180011967 126749604
  62488156 139497179    685534  46724346 120694267  18098596  89022820
 186633269 121330784  88638272    696846  93560478 198767246  92673833
  28367070  29790077 189778690 171140538  35672926  4301251

  13727224 213946497 101694850]
[200613338 141019365  61002066 166295946 100703819]
[ 58590482  12559445 190128240 103936038  59423219 204087436 182689294
 130714412 207110525  67754250 214382067 191781398  37568042 103351841
 213892560  59117471 110762245 128992629 211336301 106312275  78045066
 196536650 214641830 170606738  72737278  32358168  65616104 182570214
  49045021 197148831 127517207  69310328 166049990  88365720  96672615
  76692833 165445005   1203444   2281022 206071065  88088472 187085886
   2291025  61476326 172570545 189863871  19693551  50191582  37570256
 124329585 214930803 140069561  94561664  26458409 215002033  26764935
  17894275 168699838 152729977  15823182 101966164 110630108 158950467
 181279056  23412803 172157794  97114461 215080752 204607603  88681316
 215279260 196303869  40290389 167601868  75560529 115482917 130402320
 209917374 113345842 187845621 111923072 180575511  19096152]
[ 12902917  87964662 204516197  78485852 124754061 135280801 166902441
  

[164695461 127517207    162243 107789847 160227771 158956304  68304622
  81787512]
[ 17362365    697734 197929910  78909772  27531675   6852208 178708621
 213170586 123861555 117410193  22047196 112779308 146897414 172137409]
[181418813  95056374  88169685   7409095  88562924 143493678 107284049
 203538523 211977695  38595244  89615326]
[ 78041944 158742119  83465410 115423386 126136322   1863690]
[ 19575335   4087193 140544956  35612632 112406022  17647883 177456769
 149050799 188607328 177353888]
[90981796]
[190128240  95248575   4833779  29158940 137424223  70482877 171362825
 167678648  32106066   1882935  82701020 132522037 163964557 101875093
  81397006  42878364  38462625 111510899 182958611  82665842    299359
  94007332 129133500 188633595  17888028 203803169 172649204 192673601]
[114044787     43184  94351038 130482614   2205713  11282167 103247197
  75477702   5636085 109992648   6203383 174601939]
[142031927 183349590  25268768 110427710 144464986   9016503 107192805
  4760

[ 50698553 207189041 160738843   7203759  63488971 146068470   2276926
  66857029 151411191 152710396  16955030   9322365  83458419  45420030
  26805848   1513514  98674848 141963507  46105158  78003800 126412721
  97803960  10463697  25663102 135704461  56171901 179858327]
[ 52707476   8719956 162792689 161988020 171734747 197762839  36616828
  75258610 174652664  69474256 176456399  62828146  20534097 116544842
 203736256  77420883   6719948  33493022   6035736  80060863  74599322
  99635222  57751668   5810442  14371619 173944548 121857848   5285757
  15821354   1044256 115943739 112285972  92567831 181067938 115999681
  29326676 194555316   9070676 173412016  20345974  44904563 115201436
 155492625  17149891 105214496  12088426  96419225 130498640  29006314
  98773007  12406504 132375919  38129316  97555104 198238051 174658376]
[146607751]
[ 53281092 183152036 212696493  34718157 186515603  34348477  39196739
 122293624  42616113 118940319 148765523  19445490 177778331  92363476
 1

[214577218 214611291 215007186  91868137 133826868  64860831   7700584
 170290053]
[ 84985152 209909584  60412938 177040724   4180757  20109390  88790933
  61276009  40906226  88368756    457110]
[ 47310467  31427077 103656676  25332719   2106249  54370345  67007477
  87128952  70769246 149774656 119599896  15996399 204409338 112756445]
[205967962 177668475]
[ 61311968 203182836  14415705  41202282 168950860 126322884  61586088
 150714382   5164341 182401111 215262900  57636801]
[153538082 153541865   3263901 120667285  43033927 144837911 166295946
  61354566  38299485 189863383  49665525 138975557  87797027 144890839
 134891462  59747889 165174867]
[ 99726349  39893987  93503912 169454499  28125139  93351302  38075579
   3727201  82810170 125357974   3441417 175134101]
[201277012 210932914 185655357 153541920  62488156 214500969  43017941
 214671371 214699403 160558474 140420247  13216080 204120630  18111739
  32673744  16267201 134730965  85738341 183359558  23146161 204767316
 12760

[182422255  67686275  60053515  49085693  14449813  14887566 103720296
 137290017    595971  13739380  42700374 136938614 121706983  65750534
 212586379 111759727  78814606  28062309  94442287  20039695     17787
  53473125 173583972  14819765 141452148  20133013]
[ 98620510 134831610 181270067]
[   831314  96354966 113190080 165479946 175416215]
[63170117 12305533]
[34148164]
[110648364  18006370  82722256  10428333  88106410   5771146   3811327
  16147610  44437887 214314270 132259411  90512651  34436765 215035814
   5597728 108040793]
[197876269   8058967 204906080 190434844 151262421  17582676   2859878
    785199 130451459  87377269 150393442 214695224  14853226 214762865
  27425388  71784735 120168682 125726879   2565573  74339386 188459756
 160731900   9764260  26951466  55601922  51480045 211277879  79674575
  95880910 157547542 158735498 131381679 193607832  76956882 180505995
  95541836 129613643 152788379  79180006]
[157086508 206981326 116252522  49976572  98620510 15391062

[215363172]
[48662170]
[182422255 145250727  52713245  77203312 153380363  38820766  29690782
  27372346  75573115  75680846 192613945  93259965  34248484  27837971
 145370199  89019868  28858329 102744288 137290017  15944250 118438878
   8105285 106505807 106978523 168245313 156702646  34063313  96907668
 167879299 193751421  22542488 107659041 150070112 197884732]
[146709382 104749962  92239266 214166861 102859188  60978788  27847434
  92734218  26557164   1961181  70928492 203182836 195641835  26676319
 162924264   8481680  98952420 121453356  95702362 138092176 166739350
 188311650 206584001 213625727  61029608 211424732  36827808  51207418
 212408070 121682703  57000100  64953762 180544427  36768804  38607642
  80131431 179790844  61262725  78227076 120831609]
[207648316  88196229  52328416  35727194  94828102]
[45742542 42690369]
[65123792]
[81874191]
[ 85012410  99197714   9880579  91393229  68717709  16570153 209491607
 198581905 211216422  83905428 198848974   1479419  9472938

[2520293]
[   257421  16570153  19096152 213861850 125234319  54285317 138209106
  82153273 158130862 156676696 136745261 108200116   1460366  33561371
 210969364 125477957  15349459 178342088  54828746  16720408 195123056
  88250012 212374692  17203939   8022426]
[203770825  95838374  29302046 214409468 208173372 200011474 109715338
   4934161  74949249 178487428  83158634 167691934  97975003 214796748
 100761797  17430267  88165550 166817047 214948372 116352742  45140593
 181814785  44341556 118492961  79489992 172727868 159592318 213303509
  19631649     13405    659328  43851047   7187980 141902320  20034619
 203359162 200057786  75835012  55741878]
[12756034]
[205306914  72875219 140363913  22370603  95736512 149655139 107311738
  95551915  92124880 195617447  73605721  30380479 206897903  75350109
 178794585 176272677 119932617 124813251 214655837  44169346 103765454
 190585933  49740620  54811066 215044901  76577551 136686304 115099281
  19902541 192497723 141384966 175416215 15

   6862868 100400224 157366047 166202612 177835068]
[ 50167978  35838002 107282955  90416321 212689283]
[ 71441225  86025319 202348361  14451830]
[ 37415050 189347487]
[ 39282899 170263652]
[ 79581315 100724105]
[177589438]
[3101750]
[214569298]
[136761691]
[177952947]
[ 89275690 136157934]
[198490211 166327263 129092080 190136205]
[ 86316343    374051 178526440]
[204586641]
[ 83720323 200988951 107686316 185362812]
[ 18544025 207537685  58483988 206216934]
[153397346]
[180819859]
[195274653]
[3182908]
[87568603]
[214743098]
[159755802]
[132327306   5806620]
[106998781]
[117796754 185357113 160847997 178788538   9374237 214630157 195188433
  29495725   6050009 177366312  81905144    655463 152457375     93576
  94718921 151601689 104145461 191648229]
[178101309  44213132 153397346]
[18516496]
[177121283]
[  9990945 210535254]
[191491405    227190]
[212801937]
[   202462 213341688]
[208275717 180819859]
[123703871]
[208709766]
[155484971]
[176148006]
[188127770]
[213749943]
[    16804 1

[ 76581354 197705735  16758196  71340589     13268  18297811  59379531
  85298735 208201793 206059573 170850040  87656062  66536894  85579077
 177097533  75528661   6712431  43450796  33462965  98248450 209558961
 110062492 162868089  52034589 153116726 126537799]
[ 78227486 194084768 141490416  35270760 214476897  40481166 138209106
  25024978 192419699 178613766  55710453 190102461  23937599 180761297
   8294470  47706387  95399915 102611689  39893987 146122629 132689201]
[136423862 153541705  93818759  60978788  62364498 173572496   1501228
  55555423  56629089  95703687  82745709  54905171  71628406  42911277
  93873700 103385792  42071842    223689   3395515  54510482  90460785
 206965878 168699969  26297689]
[ 93818759 181309308 151256299 214629188 166298680  39032939 133172859
   8437421  14575858 107307846  65460371]
[   489887  60320816  82027253  99391198 101709867 191096513 170792895
  80267123 135193487  39606629 161016067 166929088 122878932 115070873
 100623191]
[13976635

 101438889 192315306 215356373  55887678 172488848   1160325]
[144780413]
[79719318 28574748]
[194750084  89804726 109674597 205884585 162477059 206878122 154554048
 162561577  96210734 176617190   9750176   3211566  96182417 142988814]
[214491021  46035504  71626910 190507926  69415865 126658138  80251115
 214905836 214932074    157195  13502862  35866282  73014706  28887725
 159135017 107919386  74670962]
[ 39883295    122554 212785646]
[ 85259921  94758861  18312478 214231890 178794585  91314718  61415716
  80018083 213342521 211269229   3790233  49434344     89350  36279258
 212098443  92657637  85187042 144532886 214596899  29794782  56308771
 115260924 165091200  33340697  36054869 168807464  12161000 111942525
   5836599    156906 125757099 204885007  53226699  55935878 181356259
 209246313  22733901  77296494  82017129  48412074  96355547  64533366
  33995258  66379158  33678283   4780524  55143493  68388221 162899941
 178491887  75560529 205052349  79281077 192394620  75084108

[123876010 197029072 160641385]
[ 26206989   8242219 207079255 152883850  99630989  56789529 215056072
  99517519]
[115193180]
[180185128 147981823 206347994 153541865 127503240  12594658  10748452
  20843082 173284851 113542223  86308323 214793732  96474917 202308601
 176012088 201546550  69268955 128608707  63598594    633839 100319913
 153541782 203802400    559350 114548218    845997  79642798  92243128]
[ 59674330 109798952  79331950  46053538  43397183 125627722 110161367
 209911934   4638158  13316768 197249099 109037400 139510629  26865478
  75564159 186719013    222573     50967     87716 160292984  26995465
 102730173  89029325   5045371   1710626 175701055    823459  47515553
 114653970  95519067  19778832  54101757  71949689  42262429  18279807
   1780827  56984530 148106035   7642742  33834238]
[141892999 138708104]
[  7416995  37637184 118497421 148100961 215018375 100335633]
[   613919  63247619  82288225 176905786 209743740 214522231  95245424
  18544025    348846 20717

[187029539  72024699 182554593 213038548  84713425 201001124  99469244
 213851604 199974696   5071496 133960976  26107753 100440364  46922861
 173940832   3351298 202701147 130968387 214769120  42405077 157204972
 202637449 100224660   1875859  11437432 141826466 202115799 214919257
  78053950  47314841 116508918 104243837 202382074 108485738  29927169
 114805703 133632892 101230078  15480472 172744412   2943274  86891928
 108200116  99076543   7936666 173180014 191092115  90872726 174777835
 170936134 119995768  27405629  61324077  86283587 214257377  86853873
 193631869 120292918 147370399 119860747]
[75562537  3814996]
[85514176 26968630 58482282]
[175041056  72456985]
[ 25894974 202771376 212645291  63464119 122288653  27486445 121259408
 184414226  12356765     79712 103047855 195523448]
[213839975 183752036  71662654 215348691]
[ 43630455 214938405  88933025   6173691]
[198536255 137517355 215256572   2982224  62123939]
[129106940 182891690  98351467   4464384 181418352   4792143

[ 30606115 175884212   1256054  81064218  75528661  89113013  51207709
  96673543  86410117   7017077  16826519 133632892  15622048   9094318
 192787960 187404470]
[121543036 110119581  14885258   7895801  31241401  41022220  27429379
  36693371 186875778 193910799  25319984 207370415  78125840  67844833]
[214356516 214069498 210102613]
[ 95793450 212422352 176204820 114918260   7857428  59920840 136701204
 104021411]
[108081512 166206100  34458806 141457596   9807170 152945046 160987977
 149947216 132033430 186436986]
[132288145]
[61415716]
[193910130]
[  2701965 129396690 195300350 107759357 193025561    762935  77643442
 125614740  88479102 103773828  80439695  77347559  83029413 101530065
 187619779 195196056 197942725  54664820  10559749]
[76232128   548084]
[211640395 148434674]
[174974844  95840962]
[571973]
[172700543 107973660]
[158007123 162454887 162790007  56768959  74224468 142031927  22186640
  87436327]
[174176253]
[  6033348 154197967  61709348]
[178330087 199090245  13

[84713425 16508445]
[152005219 213074777  53525775    666365 166928724 214640941 142731036
   6233530  15022032 175314737 173570489  16826519 172098279  85714047
 158221291 169487496 213882465  20164175   5168015]
[213895256 172711740  42629834 121640177  97079751  47269982 173242755]
[129193719]
[204747353]
[ 33524113  82826624  75513038   2687182   2738737  65887473 196487804
  13131098   5111139 211699325  83958056   6052200  69701902   9309399
  83486257 202699887  32233245   1956675 190074055 119331436 160155707
  27779113  10947516  21378187 170949266   6370851  63714483  92451001
  76602044  72783023  11049925 197980773 152654410  70057353  67732314
  28530507 157456273  64660962 165781922  42107752  83426067  13461098
  45814435 131778077  64309168  21873860  77683660  64474369  16869864
 161047803 135147800 196769173 117837543  65534615  82845389  88954988
  17112952  41722641 193238615    925922 213280272 130297421  85876444
  75252393  12545141   6557751 177489174   6476569 

  86692059 204285537  69782200  17946144 174306455  25135313   5732860]
[13163703]
[96166006]
[45615519]
[135823196  98620510  73345774 167844015  89570405  79447777  87027537
 153326409  41958446  26355036 179055453  26371834  76007144  26410057
  55755570   2800995]
[ 78429943 194798136 114918260]
[138580145  12199652]
[3421520]
[ 65133392 115066096 194395818]
[6033348]
[   989555 130602656   9160529 148326173   2004297  84751473 213089696
  40211299  34190743 110051511 177550668  30407530 215367502 208712662
 188915194]
[136676105  32462786]
[ 34216842  19510855  49019177 113150803 186488072    894602  72923391
 138097860  46998516  47856245  89573521  88252108  17656507    966326
 134848131    147050 181408706  75922128 153970490 175932750 156167878
   4145145 177407194 178144402  91720728  99621093  76005581   1591977
   6990044  13553403 150136983 194735767 142987361 215167477  71084586
   2708882 153427534   7381786  23623336  66887507 117161461 130589615
   8129847  36586370 12

[96593858]
[15955423 86247032]
[ 50167978    256846  56815243 131553209]
[183769471]
[115999655]
[ 15454725 203934208]
[  4804724  29269390  27901686  22284221  26527378 131796327]
[104069210]
[214223704]
[ 51332368  36476351 113251142  88348584   1473751]
[ 52643606  83395832 105750501]
[43608100]
[67583626]
[212946450]
[ 17738700  98686359 215269772]
[156098495]
[189834273]
[176989189]
[ 62738534  68295075  89281949 199110270 204001806 159974578  11459388
  12088426  69385930  81961709 197193727  18568435 105991806  44108290
 213614217  42096275  70278621 121059182 169821193 103287421   9019964
  40375072]
[178475872]
[190117301 201283159  62205407]
[189863048 194926613 116190613  86863003  92536570 104117651 200635114
 211724804  24042901 143161652  95710819 164366194 108067336 133959048
  14151119 197127361  87061245 149383381  29389552  14235268 201008230
 166587228 205929359 200260168 133198397 169639213   2917314  55763662
 147305796 144880012 112632410  56302618 211793631  1338

[209187738]
[191319933  89052694 204972372 134831623    454787]
[196621309]
[118022277  57900221  34004036]
[567063]
[ 57529646 202756187 213177728  32204787  99510308 145319129 151890985
  20067866  62774905  23120001 118553363  66831751  61415716 203554877
 187195226]
[118183071 121679778]
[130596370 206287369  84638968 146260669]
[194129980]
[203575407  38168203  28397495 205417358   9760535  47143434  68124986
  15418071  39971190    669769]
[171968284 180152023 213878473]
[155879834  20840528]
[160930841 159026126 110927199 204674344]
[ 4741111 51931455]
[190398908   1142516  42947373 182091857]
[28133008  1315210 77243147]
[130666518 173586288]
[52173159 22233209]
[197139705]
[69563623]
[ 74380546 173527970  72614667  48150352]
[ 52962020  14844062 145580008 150363338 141629791   5263767     16582
 141019365 106134017 146648773    899453  41872378  19026134 204958208
 117935488    412247    152368 115105117  81060540 117996730 110177954]
[138273325]
[125286972 214851606]
[2129464

[178368739]
[ 87656045 150979018]
[211031423]
[178136102]
[214655247 103529514]
[35313706]
[8714697]
[37533498]
[21043732]
[141139917  82610872  65771277  26616328 163254435  16896157   6098061
  32667393 142338597]
[ 17194763 139657662]
[ 34729299  67481923   1875859  53717793 162055664  37976199]
[ 37843911  29353137 139503106]
[198464398]
[214754422]
[ 15361940  97814031  63918776 137380803   2889129 166913729  87588707
  63391127]
[182253535 141117878]
[75538331]
[95702362]
[  6324680 195688837  35277080  76412902]
[ 68701689  14353991  56689406 101161065]
[165323361 168047831 214213796 124730560  86608601 162332796 101283508
 135466791]
[210969364]
[ 68809102 152881929  26871786  36454499  63367985 153969146   1400447
  90946979  97117914 105903932]
[92439455]
[153541920  96105350]
[171674413 177766844 208130750]
[129666348  47675077]
[198599804]
[117102233  20219029 116736399  54105629  61568605  94015386 204511561
  31279271 158616876 151742558 179955805 213909040]
[59434354  79

[104243837]
[111356485 152818041  88276761]
[114074312 212294829 148883366  42883698 103446816  85256606  90115043
  61235299]
[209337004]
[145795810]
[29149435]
[21152978 10722586]
[57445724]
[182819295]
[53124039]
[38372041]
[61075309]
[148106035]
[120704060 210853305  99755241 164532800 160854041  43114161   1099750
  49777552  20164175  17119373  72991718 160470613]
[215506551]
[93295446]
[164978900]
[165202723  89892599 136279791 214803547  20051817  62886585 195309058]
[   18942 12810438]
[116035981  46237128 204412954 211021802]
[183157170]
[36130046]
[113201819  50761765  79434174 200260168 204144852  73608877  81169069
  62420954 178918666   1815362 132628016   4733254 154502563 189331861
 170608638 118513254]
[ 23190339 121962819]
[214636810]
[111778675]
[ 98620510 184914593]
[76240159]
[51725126]
[ 61145855 205235446]
[115784953]
[ 51950257 170673214    650791]
[116452170]
[ 69152638 124058922]
[105542767]
[162160784]
[195170377]
[180664178]
[105987586]
[126572811]
[ 4481641

[88243141]
[102027962  31635074 215002723]
[44221358]
[211129707 156962937]
[195474424]
[31556279]
[117511093]
[202337088]
[100148933]
[116154560]
[ 81068464  52312570 183254117 203540805 173671511 137673450]
[200257731]
[172486256 214565039]
[17952577]
[266448]
[6043096]
[151597482]
[45038058]
[97078364]
[132177046]
[116040793]
[117499495]
[96941784]
[124307]
[155880174  86656676 100572005]
[121962954]
[175558609]
[2276926]
[1759456]
[184890204]
[183059630  67189288]
[67258242  5374895 59972266]
[132985535]
[169463927 158776840 205463941  91463165  23068322 148305423  89728060
 135735692 143208306  23431021  85116271  39318319 203067253  93258760
  72456985     86834  12695585  35933605 162844267 198053704 188131716
  32241985 215520963 101839720 215524385]
[121079503  56865029 205355054 178657429  80209546  55280190 177499302
  53065488  88878208 199808647  65173891 175663689    432930   7332979
  27830275  84228218  20044905 168556762  81203765  85960841  57133613
 183955748  128516

[59305985]
[203619683]
[16415]
[212651602]
[40555760  8673911]
[195203835]
[110591289 184103434]
[80527328]
[ 39858737  20530410 115894661 202038490]
[146802710]
[202866512]
[148478247]
[78070696]
[128698122]
[ 9057838  3812309 32434765]
[8432140]
[161291082]
[154762381]
[201599319]
[172839011]
[169597964]
[214872951]
[177648897]
[1681294]
[172042998]
[266567]
[195141361]
[   296783 139657662]
[126906262  60808795     52204]
[176855894]
[83023289]
[41313279]
[ 16577554 104201591  47126715  11123984 207021590  34925222  53150126
  61150689   6475737 148446505  12897450  67258242   7769814 102027962
  31405473  77480615 144767797  62891595 197828450 170890329 140074272
 195889593  90017074 173272296  17102310 115809205 178162374  99691479
  56360284  54318405    586702 112982178   2391794  93415440  87702307
  14416640  90053825  76811084  91868771  16049104   7148182  64693328
  28356591 120053677  28293726 174199646 132717875 213258638    647586
  11816953   4642694   5608128 201262595

[36398995]
[203352503]
[98750404]
[75097272]
[133371043]
[69564844]
[33467910]
[144837911]
[124035075]
[203802799]
[76485784]
[103895822]
[7036848]
[59356509]
[181947318  58571002]
[215028519 130531436]
[ 26058795 164639248]
[122002366]
[134839377  73596208  12202006]
[214778616]
[161740347 108421333]
[ 97115948 117934365]
[187300166  30438087  88630046   3808253   9034117   1080436  14027310
  88752464 209814218  75759230    224267   3999463 100224660  33454907
   2565573 163730013  98815200 130297902    530957 214919257 106549497
 169821193 113629762 180664178  72594526  94524997  11847663 119860747]
[179165875 132157935   5213354  88200137  41555167   7786871  42052683
 173468400 155294151   3206910  38743578]
[59525275]
[180371497 204638177 114900706 174151542 183776780]
[ 72220384 127777045   3628197  66742970 215152780]
[145795810]
[175252183  28942713]
[186015754  10972989  37109910  89291461   9176692  15089355  21860580
  27188661    762417 130625121]
[150373920]
[31044985]
[4

[ 79960226 140069561 135664584 161863666]
[150945725 150563000 214470969 156267408 110067900 215002658 147353420]
[1879179]
[140251492]
[172133839]
[50834745 90307711]
[181802458  87702307  41301996 162663019]
[62245303]
[212051007   2024532   7817275  44531817  14844062  27232509  16021925
  11414051   6851916 146085983 124725744 197849641  31104629   7363555
    791697 159969523 160618683  98620510  84244933  54905213  52997952
 209854852  63934847  97599637  61909284 213601134    259082  84411886
  19026134 145580008 107757002 151568857  50554701  54378407  94839755
  43301538  39863774  76604469  92295262   1620973 122148880  27696508
   1799529  48188601   3433129  52385832   2942003  81060540 104814026
 168547208   8842109   2606375  85681194 117319305]
[ 12658890  62039711    351744 213625727 214437948 150895133  33938584
    993204 190628110 189757863  67859366    890240  75562537 179284150
 169844189  48129567 208784344  82913805  81651969 189702473  34639083
 213835295  77606

[75582667]
[187313191 204933856 169657012  64649665]
[122929062]
[268342]
[ 21114710 149268879 141136009]
[ 55074114   2417553  12181597  18641173  14029953 199529895 178113194
  46135556  97366641 156856188  10623583 129340092 126343716  88967613
 107068719 159066665  35950426 163823512  56969018 103992076 139083888
  28817943 129376892  44056931 133809802 117880433  28516728 188131809
   5547364  21296077  59473616 195245604 210212789 214671276    261935
 160961729 112062325  59923987 139545330 154577253 199974696  94080324
    233016   5808014 211327310  43465820 111211206  56315286 133729342
 202430819 213627283 147456796 198643730 209559599 182402182  64968662
 113377199 177286363 144147057 211888147  79423686  75384041 144067521
  85336321 194829325  39589497  15892839 128199958  90929366  53073829
 174599047   1340234  91927285 214183435 178949274  55710453  48467092
 209222579  39606629  14770095  82236791 139980427 202746808  45138283
 199616657  61268026  39432155   4496130  

[ 56198722  18745467  61204571   3567234  29476290  18224364 152175142
   8860286]
[63922234]
[ 97115948  59816440  18450290   4866987 159334926  87097033  47723626
 181033491]
[116226110 181155145]
[100294218 154047149  62390478  16073245  59845610  28233664   2548413
  27306073 192843681   1307032 155506634 136167945  67837090    900246]
[4788328]
[  6048308  56268894 195216073 184419459 208963580 134082818 104056521
   2137694   6258936 203633361  95869144  43130127  53393979  48199565
  60599168    981042  24053233  17931484  31417945 103576636  76094501
 155962927  54756314 137245836  56127820  10733278  57412289 113178578
  23962466 136465606 122140523 160070266 111289761 148883366 186407560
 186785649  41958446   5028860 203528713  72115406 167661027  35309539
 211626866 182371597 160331169    763089   2617691  17984716  46683457]
[55814666]
[  7596138    861556 195357827 167911060]
[169273953]
[76696118]
[58611495]
[214881461  72529264]
[ 84397664 158374019  56991373 102992272 

[ 61194521 102381653  30356529]
[90894666]
[ 1993646 63904849 34297373 62447627]
[ 78631935  58140912  66594766 150555772  59028779    981042    248048]
[150454178 214425727  96505946  74841985 138901403]
[100345048]
[159759651  83376623  48806743]
[169699556  54897226  88790502 160277459  19706062  67038612]
[2783914]
[122636418  31329642]
[89148879]
[116620184   2444968]
[172250426 154177481]
[ 61344576 177253826 200319246 161806672 157743280  10853374 210946375
 165792813  49311069 208615143    201929  54110346]
[170772502  56530624 207435467 214529476 108078006  46045779 181494048
 160844339  58571002 192209798 197581305  92173861  59288826   5048260
 168445663 131375087  96046105 160470613 141256895]
[ 78989187 123011284  82309683 177253312 201272793 207293995  45141632
  95941535 157527130]
[157612247]
[87895737]
[ 44922157 172917748 214183435]
[129175362 137645198 159229864  41819779 119830655]
[ 28487208  64085188  67697974 119708403 215492445]
[862014]
[  3621937 172218809  49

[93965815]
[102971417]
[ 32916832  26206989 202364847 203803169]
[168998004]
[80267123 97799096]
[  6475737  53538251  48070037 125965464 109774422]
[135915216]
[161877401]
[36060453]
[154526237  74590158 206947499  81780037 166739350]
[63795609]
[204869750]
[141885320]
[198497779]
[155711428]
[207262426  27425318]
[120384811]
[   757001 152500727  86040945]
[198302096]
[42366362]
[34485226]
[6052650]
[115144407]
[165861012]
[186417043]
[145795810 105510173]
[193689962]
[42644551]
[74372395]
[25922248]
[64829749 76290513]
[151208960]
[212370483  85938922 208815830  35563088  13722282]
[64425887 22370372]
[3710167]
[1974235]
[189027099]
[ 54690339 215326026]
[81418164]
[96844068]
[149386724]
[210374490 196390973]
[142919151  15892839]
[197960696]
[102656257]
[117073054 114044990  68393630]
[126780403]
[40558104]
[241982]
[33663938]
[12584597]
[211021802 214828897 117526022 197822804 130412535]
[102560175]
[79569751 92641011]
[ 69321341 190408627]
[ 83711971 173310160  75258610  21473418

[77915663]
[119500489]
[53217385]
[72780727]
[118049883]
[140196290]
[20676824 41375040]
[17348624]
[82896649 79034937]
[1840238]
[14120681]
[204686252]
[92823391 96375032]
[ 12477022 175503238]
[65427223]
[80384891]
[197349247]
[34279823]
[121276648 183822944]
[168518872]
[144092459 152480582  97460702 169311349  78173313]
[71424313]
[116104770]
[173587391]
[190416772]
[41743227]
[214564997 213584004]
[208840601]
[ 28509723 202596177]
[ 55117798  20109215 105030690 166341355]
[22935065]
[171465913 121267851]
[106965196]
[ 28455837 166560537]
[133632892]
[18385166]
[139164756]
[124310066]
[110419993]
[198190622]
[184155573]
[214646614  77482766]
[165519617]
[208681428]
[181830690]
[14369721]
[188030296]
[101207487]
[197499464]
[132635319]
[139677892 161929904 175916914]
[52121262 80738641]
[ 7425482 24994888]
[157936293  93937504]
[204312577]
[58772851]
[128820748]
[84125419]
[93188803]
[206458065 211641613]
[153583696 121780615]
[95401650]
[61974355]
[118802002]
[22186640]
[197010411 

  18244396 166144438 215281917 215208696 164504953 215468525 166275285]
[ 99761263  13154850  37843911 117281851  39997851  75344790]
[47036544]
[   630561   3077836  91037252  85154803 164846411   4384310 191377655
  90429092 173711820 101005193 178827149  87946291  12652885 192398542
  64790087 150373920 198586058 197328971]
[67049948  3082608   559350 11356448]
[62950528   107406]
[71234858]
[ 26388317 160211151]
[215419932]
[ 33391381  75212709 214472763  59977447   8090016 206842161 172833846
 189925405 181445529 161905579  70764891 182561584]
[ 96197353 107137340 130286387 101410570     55055  82850113 164833562
  99913840 211795956 185496254  19354594  11820390 179331511  84831142
   4924530  45945442  22656148 105824557 107682955 189780346 191975619
   4965239]
[ 89009517    890239 202542936  94651663]
[207367653]
[110427185]
[38418361  5184573]
[ 95858159  17430812 193759841]
[124524380]
[2487404 8058449]
[32735863 44247612 18187575 10738740]
[31145012]
[209156366  46801275]
[

[26675829 28460696]
[56961780]
[101444198]
[ 30630379 130850655]
[132982772 208793689 153836756]
[79525869 33105194 95399773]
[137848030 168906016  81177173 156868879   8408234  57689670  68436168
 174597165]
[ 49187263  92239299   5651819 177762615  75863817 212307912 194726428
  55970271 187473835  43907454 202219674 186651144  64166368  48531114
 191559959 107474533 204490420 200370450  94865458 174306455  35851240
  35573761 215230775 141625554   9651575 200057786]
[ 99950578   8436063 134222752 196122888  13925102 149571222 120078796]
[136571182   3895646 165026646 111547523 159417194]
[183311813]
[211162660]
[119987661   5845364   7633202   8694201 213008570  78905227 164653135
 161994493 201604948 167789746 106134017   1513514  28112130 203752010
  40340412  15412268 205940927 128478059  86746169  58050432 148831931
 179329089  20174747]
[ 47730275 183963172 131391883   6778053 143883043]
[166141704 214481474 137684092 125417727  91751972]
[64547943]
[186026878  41395115]
[21169

[158048102 171675781]
[208409151  13414413  30604735  40376017  63918776  17089546  90591879
  29524850  41755160 137236183 175934342  26521177   1358532   2232542
 195190980  93786665  96046105   1256054 104165095 209321977 182244671
  67318083  21403946  63095288 119756646 132079795   4422243 181556170
 176613759  95616301  43825876  91873533  61925180  78626273 186351354
  91757010  48289634   4998979  54098779  13131098   7501333  83024846
 111271520 202177991  77354737  64164803  47651973  53304572  19579143
 197546698 103691921 103963993  37075879 211595227  46367116   7781801
   3299749  44947034 180637441 126780403 174269949   8330029 125645680
 141299328   8830199  71029983 199616657 165454736 179969709  18926037
 214744457 115270752  75577062 214798429 143384350  51510748   3636060
   6847538  87906969 192132617 190539057  35018952 204233731 135255495
 214954996  26700612 211513057 198009584   1395601]
[132118006 152582171]
[213835295 214475223 104429701  12739545]
[19846549 

[ 57475385  26433933 177232128]
[  7427696 150856952 114037912]
[ 87493255 167155414  53825606 191064944 208806320 128953033  52643606]
[204055980 102588967 192202794  58206314 192148150 184890204 207339566
 193405320 174026704  34095208]
[86462599 26988689]
[111789253  25082821  54200888   1787188  85790396   1928165  46846801
  45961237 135489646 186147599  51587145]
[111365639 194693771  72266748 178934657 214580262  64441924  88760255
   8860038   4194106]
[39566953 11417658 23804697]
[1820374 6183153]
[ 35912010 110963109 181802458   7174994  87567843  87020776   6054043
  25022471 173932983  92323497 160164703]
[ 14222843  75863817    117195    679184 155156882 154982338 153580803]
[5427815]
[147853291 174644569 110953359  16795242 137968994  49566691 215166434
   5426238  67185516]
[  2693376 127281056 203312433 105597392]
[211190964  90692301  39165518 201762365   2854040 103043353 122636418
 105531631  91632997  83863548  95723534  67609385  88561989 100815355]
[133244101]
[  

[99636563]
[  2076152  41687113 132717875]
[ 95399773  19939196  56202212  79815190 103920039  63695946    957362
  58714420]
[10204095]
[45567709 59718129]
[107991631   7769814  58903918 101599368  97380109  94714732  86405199
  71157281  40935803 196065785  25440568]
[ 30486966 215251574]
[24170827]
[105181453]
[93849426 43691864]
[5036176]
[138821415]
[124069747]
[12988772]
[ 1028958 24266212]
[69638271]
[165965202]
[1577764]
[112349753]
[181158894]
[15650576 79642798]
[ 71842849 101599368 158463221 214676300 178956843  52422128 113802973]
[ 16702920 138806692]
[56901313]
[1902431]
[215152780]
[518596]
[188184800]
[93595]
[ 92541562    513940 173618378 214769594  64945531  68375355]
[115371055]
[ 89902302    137272 127585902]
[174616241 136035785 184138210  14808449 143150597  42081837  25801967]
[  5998170  92841391 104742009 101679271 124925118 194117270]
[150827559  77995017]
[571689]
[74168335]
[3915003]
[75105799]
[181315627  88513048]
[175454537 192611623 207456648 162448231  

[93752110]
[105822253 106983784 183533985 183519481 213503680 195742003   9618690
 160804000 110419572  77134239]
[186210438 182713837 133078315 165244617  44028993 120485154  26935408
  26725557 198221762    801495  42730074 182422255  78092307  13739380
 110586340 132154450 104897524  49529143 174432621 203771047  95500119
 156873888 100253593 201552282 214754105 127777045 112958276  15991691
 131035911 111214257   1386057  55314633 154071461  91734696 181944762
  43071146    762338  49616826 151192741 190954325  73929421  88002743
 105030690 132051714  35795338   4429353  27782605  17788372 134379527
 204010369 139842418  82710828 177492533  92537427 204233731]
[ 20772526  39953847  72620944 213878473    370790 146864120  95627721
 118225618  20177265 139088122  18532860 215288319 166276462   2716486
  71459796  92322131]
[157171747  27776298]
[155695494  61767473  60725184 101350840  63281270  21473418 156336859
 203284022 194104520  17376211 194407106   2300204]
[147199086]
[17212

[159598953   5384650 214802181]
[184534630  64871078]
[23423062]
[129265094  90014243  63349432 111863784   3636060  19984377]
[214288669]
[207371687]
[7871705]
[45765677]
[ 83907958 202782377]
[ 55228265 212274810]
[112309825 167761700]
[140959692  42911277]
[173858502  50497133 110363885  99376567]
[2301729  799445]
[  7113926  25026920   3763841  91825425  47779648  41819779 151227980
   7443163 186947826  18014602 161186675   3183085  77617983 110665095
 177864152 163414829 206764580     21399 127278798  55342198 143800413
 162768919 185812339  41223059 126102467  44791449  34330300 163379694
  45289012  19519453 153194937  12739545  42653832 202687592]
[163683959]
[209293443]
[87630191]
[190572028 169232284 204755624  94962361   3955367]
[51319491 26774105]
[59423219]
[183515807]
[105304334]
[37670059]
[  4896047  48763400 136291667  76744122  75933764  62726546  90265100]
[29033195]
[66501399]
[83907958]
[214351403]
[202261647]
[101468107]
[167114985]
[4332986]
[189847309]
[19005

[134639249]
[112686757 114776891 190408627]
[120433145]
[31635074 26934538]
[96672615]
[ 70568254  61244088  88866758 110787949 191211430  28951459 141054227
  50167978 106901693 161345340  40089945  63064472  14712569 137851024]
[182879078 215498936  22351920]
[178544592  89604479]
[207671334]
[168062115]
[118469148 183618956]
[54599188]
[34053354 95788048]
[190398908]
[81947508]
[34034306]
[103855003  34712870]
[164218842]
[34817359]
[18887495]
[ 38506686 119995768]
[149177079]
[214646420  42435653    685118  20543194]
[34830398]
[127318875 212198691  42399205]
[158131584]
[101832696]
[ 59067703 114663799 172676734]
[58571002]
[84891572]
[14849174   611049 71512007 56856638 23131696 88243896]
[186737287]
[28187741]
[173023858]
[212198691]
[ 89979974 111330411  85116271]
[203342968   4187023 152619716]
[2705726]
[131315312  10796680]
[201511635]
[201498122 196583246]
[197385366]
[38372041]
[92522714]
[1315210]
[202906110]
[200712343]
[162094701]
[95681667]
[168613766]
[9447172]
[20188

[11177531]
[202756932]
[208170867 176421228  31320108 176768013 198221762 192375480  26719550
 176690067  86533931 103512744 141911062  79738013 114217098  16869864
 103731414 208046247  55423683 172570685 175158181  53426873 160804000
  14977046  91002604 154949795]
[10173890 32215616]
[130847042 112014258  25718621]
[214208798]
[93612115]
[112029592  22820980 162789967 204850996  85984209  78922637]
[155210817 122571066]
[11769899]
[139453802]
[ 57252101 178900190]
[198712914  93972424  28854344    455112  11143398  30246863]
[29635551]
[140518486]
[98901464  2038135 47080890]
[215037917]
[144532886 213677778  46357959   3588336  15726957 214538961  74030946
 202808912  61415716]
[130451459  71979496 214754972 154800276 104917106]
[163347546 106760309  40935803  41113564]
[139758405]
[35950095]
[160490718]
[ 8300472 40178270]
[76076784 89587186]
[214216163]
[ 66831441  28011885    490603   1649890 145709471 147054755  58148365
  88158809  88868692 160645352 187859225  36600043 177243

[103591203 153403612  89104135  38236378  42554656]
[155460200   2372092]
[58591324]
[ 58141666 213986971]
[192013798  10787126   1331592  39748060]
[205355054 157938429]
[ 23427115  26618507 190982113  45227093]
[ 17453541 158523156 119937179   6152728  16692556  22617660  13098036
 161280152 167169030 131606981 215179277 182754726  13128607 122449645]
[116026895 186728457]
[197105365  13312832    179518  95485822  14688048  70984964]
[ 13535905    772370  20958058  71698775 119937179  37205180]
[141885320]
[165248226  60671183 211516902  31437947 124866308]
[88388655 86865772]
[211714213  27306073  35126206]
[ 90704489 166160216  20628529 111704479]
[ 42417407 167570884]
[66762005 12862816  2360427]
[131926447  90481014]
[186728457]
[35328866]
[ 61544582 214685393 204935078 192194397  44058566 204747219]
[ 74139090  63313312 183174720   7868103   7963893  22578156 146954977
 193590144  33677104  21568373 156416744    228567  63305372 117542226
  74461666  56893175  66124632 156319797

[   236098 214958778]
[126502217 214590577]
[135342810]
[169953382 122835776   5916532 179329401]
[ 15948506   9308863  92466430  49296656 212761881  18308656  67300363
 173541980]
[160737281 155776474]
[136465606]
[ 31556279 166093334  70446221 213082080]
[193002894]
[177411357 120410560]
[199435095 208709766]
[38633826]
[ 46091479 174701151]
[157527130     12856  80070595 203817002]
[147853291]
[4924101]
[137313322  58205363 117047204 169645334 124630533 179702288]
[87028167]
[ 94689772 214508020]
[88366514]
[41689609]
[12594020]
[75343638]
[41455884]
[180387542]
[20553166]
[215234903]
[211348617    122242  19446530 178202778 189337238 134227883]
[38967424]
[19553967  1884330]
[88800596]
[145201725]
[  4345339  57115334 178614324 212936472  55776184 126502217  28494991]
[56233567]
[5802718]
[202541169]
[62281233 73537951]
[65814291]
[  1761705 157368989 156968165]
[125162017   5627531 117453023]
[181148927]
[22928902]
[206255177]
[97945812]
[158690055 204850996  48891070]
[92275977]


[129830336]
[5412085]
[189966910]
[167011073   2386582 177295709  75257056]
[83105138]
[198454044]
[139657662]
[210508776]
[101607989    549988  33462965]
[50198835]
[214909215]
[63120335]
[73269172 53580908]
[93554440]
[59073496]
[118758512]
[203619912]
[210508776]
[ 6185112 86974547]
[9491655  715642]
[174974844]
[158256272]
[75562537]
[197642661  50418974]
[121057357]
[ 17441967 134956485]
[110177954]
[179104225  97413321 121238188]
[159270743]
[12834236]
[159637368   6083430 155960588]
[80863157]
[193144402]
[70979013]
[197767082]
[214513011]
[ 1132517 36036000]
[116813529]
[214828897  80738641]
[81146964]
[177524261]
[65080828]
[61145855 53144838 33459354]
[83472178]
[102656257]
[48252298]
[195203337]
[24038395 10526332]
[194292345]
[7956892]
[89959915]
[213975472]
[197139705]
[96632374]
[7907298]
[158599726]
[214565483 138608935  60722510 203965446]
[169740521]
[73929421]
[169046011  99683761   1790216 201296641]
[103959955]
[135262216]
[72266748]
[168715081]
[214312226 215447850

[153882992  63563934]
[118401279]
[213157052]
[72081416]
[64276077  2691534]
[42172515]
[ 26931375 135315849 174640433   2223310]
[118142395  20067866 136724314]
[ 76488981 134379527]
[ 78099976 182243717]
[92341313]
[101452905]
[   233016 114282846]
[198436124  90149886]
[139317380]
[35126206]
[ 69806144 178412954 210989085]
[97220020]
[7074033]
[ 13854809  27368255  65452990 173986396  71590848]
[123865240]
[71556291]
[173314149]
[171640650 160087399 150436621]
[206940329]
[117410193]
[55605646]
[118429921]
[5537633]
[174613177   1479419 214493095   3444988]
[181802540]
[ 62826349  66746867 157862518 102933153 117358333   9358034 213595313
  54943300  89746874 111184598]
[214866456]
[107450999]
[105836742]
[208708129]
[201289968]
[100555378 214468577  65921305 163352656]
[57565]
[131926447]
[   282886 121403248]
[75643589]
[214123093  29879939 132481308   7143897 124925118]
[180504295  26523861  44225453 103571352  44167082  30805834  66435492
   1325103  99665654]
[117778099]
[ 7441

[26817820]
[47102577]
[13721631]
[192417131]
[156040805]
[174663144  62974681]
[43593597]
[20263793]
[115400698]
[101913633]
[179785954]
[151397528]
[  4219101  71366183   6195143 168807464 214179781  90077486 158788189]
[153613918]
[101489601]
[159430555 197732389]
[ 77666145 144925236  53479238]
[116765404]
[196032111]
[151177863 100789361 215200994]
[   765883 114288089 178639744  50803318 207324915  92424346 135891299
  88878185]
[ 59747066  94090661 184534317 172952277  93654136]
[215332292]
[187183520   2538885 110016388]
[ 58672436  25020624  75043525  73401688  95555289 215049712 203453922
 198107132]
[3140885]
[189147216 124483726  79642798 158851182 215003034]
[75848855]
[154010367 131713212  46281312  31059820 140304538]
[214323426]
[179331511]
[177746743 139494462]
[75887743]
[170236881 106548385    346742  83458419  51497439 102262212 198662175
 215368768 102385933 153162723]
[212578485 127264975  44167082]
[175275964]
[197093050]
[112029592  33322123  40390582  39308990]


[108228197]
[209852051  95536427 110225632]
[135291049]
[203966941  35514477]
[122067697]
[208506699]
[215101992]
[ 64563320 121031324]
[ 49630204 156891187]
[171410063]
[ 95810129 140900226]
[69349917 15626799 39257613]
[201174729]
[170304959]
[22380115]
[210544446]
[13450076]
[121228407]
[147853291]
[60863393]
[ 95842934    753950  78911819 172458174]
[60236601]
[215393529 139886670]
[20400631]
[111004389  42766291]
[158475842 202399143]
[210743380  80466843]
[54137522]
[87511534]
[87187746]
[151232380  29426301]
[124866308]
[125595125  57138742]
[69146041]
[90750423 21207141]
[168026397]
[67844833]
[79481714 15758586]
[884113]
[61381289]
[179122782]
[66858047]
[26494615]
[  3235354   3865864 121254702 158776840]
[61002066]
[214988128 114808783]
[71366183]
[132323650]
[211674712]
[50167978]
[383751]
[72961080]
[95399773]
[209831732]
[ 87964662  90077486  41024174  69311942 142650868  38163030 169046011
  56459985]
[185409691]
[6043096]
[39539977  8393902]
[205629102   3483931 1670176